name: Run Python Script

on: [push, pull_request]

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Python script
      run: python app.py
